os: osx
osx_image: xcode11.3
language: swift
script: xcodebuild clean build test -project Tomate/Tomate.xcodeproj -scheme "Tomate" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=11.4,name=iPhone 8" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO

